"""Language configuration for Echolingo.

This module provides the single source of truth for all 65 supported languages,
including their compatibility with STT, translation, and TTS providers.
"""

from __future__ import annotations

SUPPORTED_LANGUAGES: list[dict] = [
    {
        "name": "Afrikaans",
        "code": "af",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Albanian",
        "code": "sq",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Amharic",
        "code": "am",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Arabic",
        "code": "ar",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Basque",
        "code": "eu",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Bengali",
        "code": "bn",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Bosnian",
        "code": "bs",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Bulgarian",
        "code": "bg",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Catalan",
        "code": "ca",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Chinese (Simplified)",
        "code": "zh-CN",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Chinese (Traditional)",
        "code": "zh-TW",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Croatian",
        "code": "hr",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Czech",
        "code": "cs",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Danish",
        "code": "da",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Dutch",
        "code": "nl",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "English",
        "code": "en",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Estonian",
        "code": "et",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Filipino",
        "code": "tl",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Finnish",
        "code": "fi",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "French",
        "code": "fr",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Galician",
        "code": "gl",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "German",
        "code": "de",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Greek",
        "code": "el",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Gujarati",
        "code": "gu",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Hausa",
        "code": "ha",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Hebrew",
        "code": "iw",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Hindi",
        "code": "hi",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Hungarian",
        "code": "hu",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Icelandic",
        "code": "is",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Indonesian",
        "code": "id",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Italian",
        "code": "it",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Japanese",
        "code": "ja",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Javanese",
        "code": "jw",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Kannada",
        "code": "kn",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Khmer",
        "code": "km",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Korean",
        "code": "ko",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Latin",
        "code": "la",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Latvian",
        "code": "lv",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Lithuanian",
        "code": "lt",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Malay",
        "code": "ms",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Malayalam",
        "code": "ml",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Marathi",
        "code": "mr",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Myanmar (Burmese)",
        "code": "my",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Nepali",
        "code": "ne",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Norwegian",
        "code": "no",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Polish",
        "code": "pl",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Portuguese",
        "code": "pt",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Punjabi (Gurmukhi)",
        "code": "pa",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Romanian",
        "code": "ro",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Russian",
        "code": "ru",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Serbian",
        "code": "sr",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Sinhala",
        "code": "si",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Slovak",
        "code": "sk",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Spanish",
        "code": "es",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Sundanese",
        "code": "su",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Swahili",
        "code": "sw",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Swedish",
        "code": "sv",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Tamil",
        "code": "ta",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Telugu",
        "code": "te",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Thai",
        "code": "th",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Turkish",
        "code": "tr",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Ukrainian",
        "code": "uk",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Urdu",
        "code": "ur",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Vietnamese",
        "code": "vi",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
    {
        "name": "Welsh",
        "code": "cy",
        "stt": True,
        "translation": True,
        "tts": True,
        "status": "supported",
    },
]

# Validation: Ensure exactly 65 languages
assert len(SUPPORTED_LANGUAGES) == 65, f"Expected 65 languages, got {len(SUPPORTED_LANGUAGES)}"

# Validation: Ensure unique language codes
codes = [lang["code"] for lang in SUPPORTED_LANGUAGES]
assert len(codes) == len(set(codes)), "Duplicate language codes found"

# Validation: Ensure unique language names
names = [lang["name"] for lang in SUPPORTED_LANGUAGES]
assert len(names) == len(set(names)), "Duplicate language names found"

# Validation: Ensure all languages have required fields
for lang in SUPPORTED_LANGUAGES:
    assert all(key in lang for key in ["name", "code", "stt", "translation", "tts", "status"]), \
        f"Language {lang} missing required fields"

# Create convenience mappings
LANGUAGE_CODE_TO_NAME: dict[str, str] = {lang["code"]: lang["name"] for lang in SUPPORTED_LANGUAGES}
LANGUAGE_NAME_TO_CODE: dict[str, str] = {lang["name"]: lang["code"] for lang in SUPPORTED_LANGUAGES}

# Filter for end-to-end supported languages (all three stages)
END_TO_END_LANGUAGES: list[dict] = [
    lang for lang in SUPPORTED_LANGUAGES
    if lang["stt"] and lang["translation"] and lang["tts"]
]

assert len(END_TO_END_LANGUAGES) == 65, f"Expected 65 end-to-end languages, got {len(END_TO_END_LANGUAGES)}"
